### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jfranciswebdesign** [ministryofjustice/record-a-goose-sighting#21] opened 2020-03-11 10:32 UTC
https://github.com/ministryofjustice/record-a-goose-sighting/
These two links are broken:

"There is a [worksheet](https://github.com/ministryofjustice/record-a-goose-sighting/blob/master/worksheet.md), and there is also a list of [answers](https://github.com/ministryofjustice/record-a-goose-sighting/blob/master/answers.md) - but give it the full 20 minutes before you look at the answers first, if you're working through this alone!"

I suspect they should be going here instead:

"There is a [worksheet](https://record-a-goose-sighting.herokuapp.com/steps/worksheet), and there is also a list of [answers](https://record-a-goose-sighting.herokuapp.com/steps/answers) - but give it the full 20 minutes before you look at the answers first, if you're working through this alone!"

**Comment by BNewing** [comment] 2020-03-18 17:01
Thank you for flagging this! I moved them into the site itself, and forgot about those links! I'll fix that now.

**Comment by BNewing** [comment] 2020-03-18 17:03
I've fixed this in the README. Is there anywhere else you've seen these broken links?

**Comment by jfranciswebdesign** [comment] 2020-03-19 12:21
Hi - thanks for fixing. I haven't seen any other issues.

I was planning on running two session with two groups in my office this week - however, due to _the ongoing situation_ that is not going to happen. I might try and do it remotely, but I think having people in the same physical space, working in pairs, would be the ideal scenario, so I may wait and see...

**Comment by BNewing** [comment] 2020-04-20 15:20
I'm going to trial running it remotely myself, next week :) One of the benefits of running it in person is getting to troubleshoot people's set up (tabbing not being turned on in Safari, Firefox etc), which is a pretty huge benefit, and one of the main purposes of the workshop. So it'll be interesting to see how it goes and if it's still useful! Something else I've been doing lately is demos of accessibility testing using a checklist, which isn't interactive, but seems to have been going okay so far!

I'm going to close this now as the issue is resolved - but happy to chat more about running this remotely on Twitter or the a11y slack!

**Closed as completed** 2020-04-20 15:20 UTC
